# Generated by Django 5.2.3 on 2025-07-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
            ],
        ),
    ]
