# Generated by Django 5.2.3 on 2025-07-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='Contact',
        ),
    ]
